### ISSUE TITLE
Мелкие несоответствия макету

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#1]
Галочка меньше, нет градиента
![image](https://user-images.githubusercontent.com/66846004/110535371-3c4d1f80-8131-11eb-8198-c3eb74c31a1c.png)

У радио маленький кружок, у тоггла слишком близко к краю стоят
![image](https://user-images.githubusercontent.com/66846004/110535651-9b129900-8131-11eb-82ac-cf809d60cd7b.png)

Более двух символов на лайке. Еще проверь цвет текста, рамку, соответствуют ли они макету
![image](https://user-images.githubusercontent.com/66846004/110541825-53900b00-8139-11eb-8827-88e6f7ae7dda.png)

У цветной кнопки не должно быть рамки. У белой рамка градиентная
![image](https://user-images.githubusercontent.com/66846004/110536195-3ad02700-8132-11eb-90a7-46e751638bde.png)

Скругление угра, двойная рамка
![image](https://user-images.githubusercontent.com/66846004/110536582-af0aca80-8132-11eb-8be2-1af6a3edb664.png)

Не тот шрифт
![image](https://user-images.githubusercontent.com/66846004/110536977-22144100-8133-11eb-97aa-73069154c05b.png)

Это нужно поправить
![image](https://user-images.githubusercontent.com/66846004/110537089-4a03a480-8133-11eb-9801-76ab2998f251.png)

Скруглить углы
![image](https://user-images.githubusercontent.com/66846004/110537177-643d8280-8133-11eb-9a11-f3d611c65266.png)

Стрелка слишком близко к краю
![image](https://user-images.githubusercontent.com/66846004/110537298-90590380-8133-11eb-97cc-d877972fd9d8.png)

**Comment by kate-fsd** [comment]
Градиент
![image](https://user-images.githubusercontent.com/66846004/110539326-2726bf80-8136-11eb-8b15-fdea296a2c08.png)

**Comment by kate-fsd** [comment]
Тоже градиент
![image](https://user-images.githubusercontent.com/66846004/110539572-7bca3a80-8136-11eb-9f2c-5b49c6fd1d65.png)

**Comment by Euyevnc** [comment]
В коммите я уже всё описал. Хотя ещё один момент есть, я оутлайн глобально убрал, вместо него поставил при фокусе  тень, просто потому что у неё куда более предсказуемое поведение, тут никаких подводных камней нет?

**Comment by kate-fsd** [comment]
Сделай галочку побольше
![image](https://user-images.githubusercontent.com/66846004/111433984-0949f380-8710-11eb-82d8-73d4dc82b55e.png)
![image](https://user-images.githubusercontent.com/66846004/111434009-12d35b80-8710-11eb-855f-42d31753b748.png)

**Comment by kate-fsd** [comment]
Градиент
![image](https://user-images.githubusercontent.com/66846004/111435648-1536b500-8712-11eb-92b2-80a10066734f.png)

**Comment by kate-fsd** [comment]
> В коммите я уже всё описал. Хотя ещё один момент есть, я оутлайн глобально убрал, вместо него поставил при фокусе тень, просто потому что у неё куда более предсказуемое поведение, тут никаких подводных камней нет?

Думаю все нормально)

**Comment by kate-fsd** [comment]
Галочки остались маленькими
![image](https://user-images.githubusercontent.com/66846004/112524862-59305680-8db1-11eb-902a-4a7a17b4e0ed.png)

**Comment by kate-fsd** [comment]
> Градиент
> ![image](https://user-images.githubusercontent.com/66846004/111435648-1536b500-8712-11eb-92b2-80a10066734f.png)

Остались неградиентными

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/113207507-5d5ce800-9279-11eb-902d-685c6332f4f9.png)
тоже

**Comment by kate-fsd** [comment]
Светло зеленая полоска, размер шариков
![image](https://user-images.githubusercontent.com/66846004/113207991-fa1f8580-9279-11eb-8554-04d3a0467d1f.png)
![image](https://user-images.githubusercontent.com/66846004/113208074-10c5dc80-927a-11eb-8bbe-2364cf525fe6.png)

**Comment by kate-fsd** [comment]
Не сделано

**Comment by kate-fsd** [comment]
> Светло зеленая полоска, размер шариков

не сделано
