### ISSUE TITLE
Переоткрыть ишью

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#16]
Есть закрытые ишью, в которых не все исправлено, я переоткрыть не могу. Там проверь последний блок замечаний 
#1 (туда еще можно добавить что кругляши на toggle и radio стали квадратами:) и тело слайдера - светло зеленое, исправить на белый)
#4

**Comment by Euyevnc** [comment]
Открыл, 
проблема с квадратами была , когда я сменил подключение шрифтов с локального на npm, но в последней версии это исправлено).
На этой странице всё уже нормально выглядит? 
https://euyevnc.github.io/Ui-kit-and-SitePages/Registration.html

**Comment by kate-fsd** [comment]
Да, квадратов нет, остальное в другие дописала
