### ISSUE TITLE
Ненужные файлы

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#19]
tsconfig.json  если ts нет в проекте - убрать

index.html
![image](https://user-images.githubusercontent.com/66846004/112530771-e70f4000-8db7-11eb-9246-a095ea576892.png)

webpack.config вытащить из подпапки, если он у тебя один файл
![image](https://user-images.githubusercontent.com/66846004/112531117-41100580-8db8-11eb-987f-eba8e9cfcc9a.png)

Такого не должно быть, чем бы это не было)
![image](https://user-images.githubusercontent.com/66846004/112531177-51c07b80-8db8-11eb-8a49-d062b4fe81b5.png)

**Comment by kate-fsd** [comment]
Если эта папка используется для общих для всего проекта картинок, то лучше ее так и назвать images. Если стрелочка у тебя это блок, то она должна лежать в папке с блоками. Либо можно сделать svg-спрайт/иконочный шрифт(icomoon). Не очень хорошая идея держать pug и scss среди картинок
Помимо static, еще есть папка assets, папка utils. Не заглядывая внутрь сложно разобраться, где что и зачем их так много. Предлагаю ограничиться одной (или вообще убрать их)
![image](https://user-images.githubusercontent.com/66846004/113215571-b6317e00-9283-11eb-9eb1-4b4f7110b8fe.png)

**Comment by kate-fsd** [comment]
Еще обрати внимание на именование. Придерживайся одного стиля. Тут caps, с большой буквы, с маленькой, через -, через _

**Comment by Euyevnc** [comment]
Насчёт именований, я оставил с большой буквы папки в pages и UI-kit, ну потому что они так и называются

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/117059810-dd6ae780-ad28-11eb-9d9c-33b22263f755.png)

Нужно избавиться от всего ненужного в файлах index. Стили - в папку со стилями, шаблон для юи - в шаблоны..
