### ISSUE TITLE
Курсор pointer

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#2]
Добавить курсор pointer везде, где он необходим. Например в дропдаунах

**Comment by kate-fsd** [comment]
И наоборот, убрать на звездочках в карточках комнат, так как никакого действия по клику не происходит

**Comment by Euyevnc** [comment]
Со звёзд поинтер снял, на дропдаунах у меня, вроде, висели везде, кроме инпута со счётчиком, поэтому у него задал поинтер стрелке
