### ISSUE TITLE
Классы

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#27]
Сейчас с js все не очень хорошо, есть классы пустышки, есть не классы. Я с трудом понимаю что и зачем происходит в коде ниже. Эта функция импортируется и вызывается в других компонентах многократно, то есть ты каждый раз, в каждом календаре, дропдауне на странице создаешь для каждого такого элемента экземпляр класса. У тебя создается куча ничего не делающих экземпляров. Повтори пожалуйста тему классов на learn.javascipt https://learn.javascript.ru/classes

![image](https://user-images.githubusercontent.com/66846004/114231607-53c33680-9983-11eb-88e8-a21b6d9c42a2.png)

**Comment by kate-fsd** [comment]
Когда ты создаешь экземпляр класса, передаешь в аргументах элемент. В конструкторе сохраняешь этот элемент в this. Если необходимо, можно добавить внутренние элементы. Добавляешь обработчики событий. У методов должно быть четкое разделение, что является внутренним (приватным) и не должно использоваться извне, а что - публичным. Здесь можно обойтись без публичных методов, просто создать в этом же файле экземпляр класса. Можно сделать и по другому, создавать экземпляр в других классах, например

Пример:
```
class LikeButton {
  constructor($likeButton) {
    this.$likeButton = $likeButton;
    this.$likeButton.onclick = handleButtonClick;
  }
  ...
}

$('.js-like-button').each($el => new LikeButton($el));
```

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/114234114-fdf08d80-9986-11eb-9dce-9020c12257bc.png)

![image](https://user-images.githubusercontent.com/66846004/114234072-efa27180-9986-11eb-81be-748754bc8181.png)

Сделай jquery видимым глобально
Все импорты - в верху страницы
Самое важное:
.js-date-mask input
Здесь ты из одного "компонента" date-mask залазишь в другой - textfield и что то там меняешь. Этого делать нельзя. 
Компонент в кавычках потому что date-mask - это не компонент. Это модификация textfield

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/115957354-8e43dc00-a50a-11eb-87e1-45b6aec8f3cf.png)

Здесь не нужно передавать root по умолчанию, это должен быть обязательный аргумент. Допустим на странице есть несколько таких элементов (.js-textfield), а все классы без переданного параметра root будут созданы для первого элемента на странице.

init в этом случае лучше вызывать прямо в конструкторе, так как предполагается что этот класс нужен именно для создания маски) а так приходится совершать лишнее действие для ее добавления

**Comment by Euyevnc** [comment]
Исправил, просто предполагалось, что без параметров конструктор будет вызываться в случаях, если больше одного элемента на странице нет и быть не должно, в особенности это касается хедеров, футеров, сайдбаров и т.п.

**Comment by kate-fsd** [comment]
Тут еще есть проблема. Сейчас ты root, textfield записываешь в this, но не используешь их больше нигде
