### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#28]
![image](https://user-images.githubusercontent.com/66846004/115957468-5f7a3580-a50b-11eb-9b85-17c9e4c5f291.png)

Такая стрелочка - это элемент компонента дропдаун, а не textfield. Просто инпут с такой стрелкой не имеет смысла

**Comment by kate-fsd** [comment]
isSimple - не совсем понятно о чем речь. Лучше withButtons

**Comment by kate-fsd** [comment]
еще можно input-with-counter назвать dropdown, меньше букв) на твое усмотрение

**Comment by kate-fsd** [comment]
подскажи, что здесь значит concat, form1, form2

**Comment by kate-fsd** [comment]
отступы рядом с = сделай одинаковыми везде
![image](https://user-images.githubusercontent.com/66846004/115958059-6a829500-a50e-11eb-85c6-a4506fa98d3d.png)

и по всему  проекту

**Comment by Euyevnc** [comment]
form1, form2 и т.д - это формы слов, которые изменяются в зависимости от числа - кровать, кровати, кроватей и т.п.
А атрибут concat указывает на то, будут ли данные с этого счётчика выведены в поле отдельно или нужно пробросить их в следующий, где они просуммируются с его данными и (если у того concat указан как false) выведутся уже под его параметрами forms. 
 Это можно понять лучше на примере счётчика гостей (из-за него это и было сделано). Там "Взрослые" и "Дети" не выводятся по отдельности, а выводятся в категории "Гости". Так для первого счётчик установлен concat: true, а формы второго  в значения  "гость", "гости" и т.д. Если бы нужно было бы, например,  объединить 3 категории, то так же можно было бы для второго счётчика тоже указать concat: true, а  слова для этого объеденённого значения задать в третьем счётчике

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/117064800-540ae380-ad2f-11eb-8bd7-01194ed13884.png)

эти кнопки можно взять в компонентах, чтобы не дублировать стили

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/117065811-9b45a400-ad30-11eb-9e4f-d3f9f1c18a7c.png)
font-family

**Comment by kate-fsd** [comment]
this.textfieldObject  это не объект

**Comment by kate-fsd** [comment]
dropdown__button_visible-delete
это два разных модификатора

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/117067225-69354180-ad32-11eb-981d-af0ad1bb34d5.png)

это похоже остатки старого кода

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/117067433-adc0dd00-ad32-11eb-8abd-6b1504f2c8ed.png)

как то нелогично получается)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/117067885-3dff2200-ad33-11eb-9b22-5fe8a3c39788.png)

поменяем кнопки местами и все сломается

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/117068206-a5b56d00-ad33-11eb-9521-09a3d5eff033.png)

можно эти form передать в дата-атрибут одним объектом, на твое усмотрение
