### ISSUE TITLE
Слайдер

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#3]
![Peek 2021-03-10 00-11](https://user-images.githubusercontent.com/66846004/110538593-41ac6900-8135-11eb-842f-744cc8deedaa.gif)

Этот ишью можно оставить на потом, поправить когда разберемся со вторым заданием)

**Comment by Euyevnc** [comment]
Я это всё-таки исправил, слайдер-то в этом проекте был не мой, я в интернете какой-то плагин нашёл и приспособил для своих нужд,  он изначально через input с типом range был написан, может поэтому и работал так странно. 
Теперь, когда добавил свой слайдер обнаружил в нём недочёт, который проявляется если тамблеры достаточно маленькие. Курсор "дребезжит", перескакивает с поинтера на стандартный при быстром перемещении. Позже исправлю, не думаю, что это будет сложно)
