### ISSUE TITLE
pug

### ISSUE THREAD

**Issue by mglknFSD** [Euyevnc/Ui-kit-and-SitePages#33]
Для чего вы задаете эти значения по умолчанию по всему коду?

![destr](https://user-images.githubusercontent.com/75975369/126866356-64655a72-54d1-4b10-8e53-2cf5d0205b8c.jpg)

**Comment by mglknFSD** [comment]
Давай все таки немного форматировать pug файлы, и между импортами, миксинами, блоками вставлять пустые строки, и где возможно не выходить за пределы 80 символов в строку.

![blocks](https://user-images.githubusercontent.com/75975369/126866530-5299eaaf-e160-44b8-8ec2-158d5a53b07a.jpg)

![formatting](https://user-images.githubusercontent.com/75975369/126866531-a077d55b-ae3e-452f-84a1-accb585850ca.jpg)

**Comment by mglknFSD** [comment]
Если ожидается, что мы какие-то данные получаем из сети, то лучше эти данные не хардкодить а записать в конфиг, брать их него и передавать в компонент.

![hardcode](https://user-images.githubusercontent.com/75975369/126866662-93bb7e5b-f6e1-45d2-9e14-1d765c114247.jpg)

+ не понятно зачем ты передаешь строки отмеченные фиолетовым.

**Comment by mglknFSD** [comment]
Именование некоторых классов недопустимо (не семантическое именование)

![naming](https://user-images.githubusercontent.com/75975369/126866727-e070db0b-c34e-4141-a40f-74db3332947f.jpg)

**Comment by Euyevnc** [comment]
> 
> 
> Если ожидается, что мы какие-то данные получаем из сети, то лучше эти данные не хардкодить а записать в конфиг, брать их него и передавать в компонент.
> 
> ![hardcode](https://user-images.githubusercontent.com/75975369/126866662-93bb7e5b-f6e1-45d2-9e14-1d765c114247.jpg)
> 
>     * не понятно зачем ты передаешь строки отмеченные фиолетовым.

Предыдущий ревьюер сказал,  что все русские слова должны передаваться в компоненты, вроде, для эмуляции переключения языков.  
А где их стоит определять? В js-e захардкодить?

**Comment by mglknFSD** [comment]
> > Если ожидается, что мы какие-то данные получаем из сети, то лучше эти данные не хардкодить а записать в конфиг, брать их него и передавать в компонент.
> > ![hardcode](https://user-images.githubusercontent.com/75975369/126866662-93bb7e5b-f6e1-45d2-9e14-1d765c114247.jpg)
> > ```
> > * не понятно зачем ты передаешь строки отмеченные фиолетовым.
> > ```
> 
> Предыдущий ревьюер сказал, что все русские слова должны передаваться в компоненты, вроде, для эмуляции переключения языков.
> А где их стоит определять? В js-e захардкодить?

Ну оставь так.

**Comment by mglknFSD** [comment]
Пустых тегов быть не должно, каждый тег должен иметь класс (даже если для него нет явных стилей). Это нужно для лучшей читаемости, с классом тег приобретает семантику.

![empty tag](https://user-images.githubusercontent.com/75975369/132123986-a42c9f72-e829-436f-a46a-f7f7dd1f6623.jpg)
