### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by mglknFSD** [Euyevnc/Ui-kit-and-SitePages#35]
Footer должен быть прижат к низу да же есть нет контента.

![footer](https://user-images.githubusercontent.com/75975369/126867069-a454a5a1-83f7-4b9b-bcd2-1d314b6f7b9d.jpg)

**Comment by mglknFSD** [comment]
Что не работает, может я не так смотрю?


https://user-images.githubusercontent.com/75975369/132125336-4f92bb97-8c45-4400-bd9b-9df3acfd0afc.mp4

**Comment by Euyevnc** [comment]
У меня все страницы layout используют, куда тэг main вшит. Я задаю минимальную высоту  в 100vh (минус высота хедера) для элемента внутри, что проблему с футером решает. Такое решение вроде используется, ну и в моём случае никаких накладок с ним не увидел. Просто в Вашем примере этот тэг удаляется извне, и из-за этого всё схлопывается)

**Comment by mglknFSD** [comment]
Вот тег main не удален, все схлопнулось. Мне кажется тут нужно более надежное решение которое ни от чего не зависит. Его не сложно реализовать.

https://user-images.githubusercontent.com/75975369/133123966-1e325eb2-335f-4ea2-a4d9-e046ac757b0c.mp4
