### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by mglknFSD** [Euyevnc/Ui-kit-and-SitePages#36]
В проекте обязательно должен быть favicon.ico, подключаемый на всех страницах.

**Comment by mglknFSD** [comment]
Извини, я что-то не понял как работает твое решение. Не мог бы ты продемонстрировать и для, например, страницы поиска показывать другую фавиконку.

**Comment by mglknFSD** [comment]
И почему скрипт который ты используешь в src лежит в ассетах?

**Comment by Euyevnc** [comment]
Просто тэги, связанные с favicon'ом в layout'e лежат, чтобы не прописывать на каждой странице, на конкретной странице иконка меняется просто записыванием тэгов поверх шаблонных в блоке head. Скрипт перенёс в layout, конечно не очень красиво, что таким  способом приходится добавлять ресурсы в сборку, но как их нормально подтягивать из тэга head пока не придумал, HtmlWebpackPlugin же такой возможности не предоставляет, как я понял?
