### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by mglknFSD** [Euyevnc/Ui-kit-and-SitePages#37]
Убедитесь что шрифты подключены в соответствии с бестпрактис.

**Comment by mglknFSD** [comment]
Не исправлено.

**Comment by Euyevnc** [comment]
Помимо прочего добавил в head font-face'ы, в БП рекомендовали и достаточно удобно, не нужно тянуть их из каждого места, где они используются. Но есть побочный эффект в виде того, что их пришлось добавлять в зависимости проекта через скрипт, который в layout лежит, опять же из-за того, что как из head их затребовать напрямую ума не приложу

**Comment by mglknFSD** [comment]
- зачем тут нужен .ttf? (Не то что бы это большая ошибка, но в проекте не должно быть ничего лишнего)
- почему декларация шрифтор прямо в шаблоне? 

![ttf](https://user-images.githubusercontent.com/75975369/133115621-5c777bbb-7dbd-47d0-92e6-1f829ec65544.jpg)




> 
> 
> Помимо прочего добавил в head font-face'ы, в БП рекомендовали и достаточно удобно, не нужно тянуть их из каждого места, где они используются. Но есть побочный эффект в виде того, что их пришлось добавлять в зависимости проекта через скрипт, который в layout лежит, опять же из-за того, что как из head их затребовать напрямую ума не приложу

Я что-то не припомню такие рекомендации, не мог бы ты мне указать где это такое рекомендовано?

**Comment by Euyevnc** [comment]
Я это увидел здесь : https://web.dev/font-best-practices/

> Inline font declarations 
Most sites would strongly benefit from inlining font declarations and other critical styling in the <head> of the main document rather than including them in an external stylesheet. This allows the browser to discover the font declarations sooner as the browser doesn't need to wait for the external stylesheet to download.

**Comment by mglknFSD** [comment]
> Я это увидел здесь : https://web.dev/font-best-practices/

Давай, все же, будем опираться на наши [best practices](https://github.com/fullstack-development/front-end-best-practices). Возможно все что описано в этой статье имеет смысл, а может "выхлоп" от этих манипуляций того не стоит, это дискуссионный момент, и если эта практика попадет в наши best practice, тогда так нужно будет делать.

**Comment by mglknFSD** [comment]
Я не понял что ты исправил, я не нашел css файла с шрифтами.
