### ISSUE TITLE
Plug-in libraries

### ISSUE THREAD

**Issue by mglknFSD** [Euyevnc/Ui-kit-and-SitePages#39]
Все подключаемые библиотеки должны быть максимально абстрагированы от реализации проекта. Т.е. они должны использоваться 'под капотом', но при этом не сильно влиять на код.
Т.е. если либы требуют подключения своих скриптов/стилей непосредственно - то для этого должна быть отдельная папка(для всех используемых либ), где будут лежат стили и скрипты этих либ.
А твои компоненты должны быть реализованы твоей архитектурой, но просто с использованием файлов либы.

Например, range slider должен быть по минимум связан с либой которую ты используешь - все стили и скрипты из блока range-slider нужно будет вынести.

Т е, например. ты хочешь подключить slider. Создаешь libs/slider в index.js ты пишешь класс Slider где описываешь инициализацию этого слайдера, slider.css - переопределяшь стили и т д. А в компоненте Slider ты подключаешь свою библиотеку. Нужно это что бы код твоего компонента не зависел от используемой библиотеки, и ты, в идеале, бы мог подключить другую библиотеку не меняя код самого компонента.

**Comment by mglknFSD** [comment]
А по какой причине ты скопипастил библиотеку? Почему нельзя было ее импортировать из npm? Поясни пожалуйста.

Такой подход плох, потому-что если тебе нужно будет ее обновить тебе придется копипастить ее новую версию опять в исходники.

![lib](https://user-images.githubusercontent.com/75975369/132123169-7c5d2aa1-4c17-46b2-8688-9117694511c6.jpg)

**Comment by Euyevnc** [comment]
maskinput заменил на npm пакет, просто уже забыл, что он там лежит, хотя  на самом деле он, как и остальные  плагины, не обновлялся уже несколько лет) Но что касается дэйт-пикеров, тут дело в том, что я ещё когда начинал делать проект их загрузил, но они работали не вполне так как требовалось, я туда внёс кое-какие изменения, потом ещё и ещё. В общем, порядком их изменил. Сейчас всё работает хорошо, по крайней мере, я никаких недочётов не обнаружил. Так что в этом случае заменить на пакеты, увы, не могу

**Comment by mglknFSD** [comment]
> 
> 
> maskinput заменил на npm пакет, просто уже забыл, что он там лежит, хотя на самом деле он, как и остальные плагины, не обновлялся уже несколько лет) Но что касается дэйт-пикеров, тут дело в том, что я ещё когда начинал делать проект их загрузил, но они работали не вполне так как требовалось, я туда внёс кое-какие изменения, потом ещё и ещё. В общем, порядком их изменил. Сейчас всё работает хорошо, по крайней мере, я никаких недочётов не обнаружил. Так что в этом случае заменить на пакеты, увы, не могу

Ну это плохая практика брать исходники библиотеки, копипастить себе, что-то в них менять, а потом разбирайся что в них не работает... Нужно либо изначально подбирать достаточно кастомизируемую билиотеку, что бы ее не надо было поддерживать (а обновлять npm в случает выхода новых версий), либо писать все самому (что менее предпочитительно - т е этот код придется поддерживать). Промежуточное состояние (это как ты сделал), наихудший вариант - этот код не ты писал, но тебе его придется поддерживать. Это нужно исправить. Моя рекомендация - найди нориальную библиотеку, напиши прокси.

**Comment by mglknFSD** [comment]
Для этого тоже нужно написать обертку.

![proxy](https://user-images.githubusercontent.com/75975369/133119441-48efd47a-d1ec-4402-a885-0faa3c1c8347.jpg)
