### ISSUE TITLE
Разное

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#4]
После нажатия на "очистить" кружок остается полупрозрачным
![Peek 2021-03-10 00-06](https://user-images.githubusercontent.com/66846004/110538081-9d2a2700-8134-11eb-875e-83a21f9554cf.gif)

В карточке room-details когда отводишь мышку стрелочки исчезают с задержкой

В кнопках лучше не делать текст черным при фокусе, смотрится грубовато

**Comment by Euyevnc** [comment]
Первые 2 замечания исправил, а что касается текста, то да, выглядит это не очень, я забыл его убрать с самих страниц, больше на UI-kit смотрел, а от туда как раз его убрал. Ну, тут достаточно пересобрать страницы и этот ужас исчезнет, я как раз буду делать это для следующего ишью

**Comment by kate-fsd** [comment]
Поправь обводку
![image](https://user-images.githubusercontent.com/66846004/111436258-d2291180-8712-11eb-84e5-9c9ade6d4bbb.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/111447338-677dd300-871e-11eb-82f4-4d2631757889.png)
