### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#5]
У меня большие расхождения с макетами. Если у тебя их нет, скинь мне пожалуйста свои картинки. Если есть - нужно все поправить. Еще по ходу проверяй цвета и размеры шрифтов

**Comment by Euyevnc** [comment]
Сейчас поправляю, буду оставлять тут некоторые  вопросы или пояснения)

На страницы регистрации панель расположена не по центру, а смещена немного вправо, я подумал, что так не было задумано, тем более, что на странице авторизации панель располагается ровно по центру, и отцентрировал, поэтому тут у меня небольшие расхождения с макетом
![Без имени-2](https://user-images.githubusercontent.com/71395653/111033459-e08dd980-8443-11eb-8063-ca9cbb1b6eb3.png)

Заметил, что некоторые несоответствия возникают из-за того, что текстовые элементы в макете располагаются на линии иначе, чем в браузере, вот например элемент с шрифтом 14 и высотой строки 24:
![Без имени-7](https://user-images.githubusercontent.com/71395653/111034392-f7cec600-8447-11eb-9367-11008b74ff5c.png)
Текст тут не центрируется по вертикали, а расположен ближе к верху, из-за этого есть небольшие расхождения в положении текста в макете и на странице. Я подгонял, на всякий случай,  где это можно было, уменьшая отступ сверху и уменьшая снизу.  Вопрос на будущее, мне нужно ориентироваться на свойства, указаны на figme или на визуал, если между ними есть противоречия?

**Comment by Euyevnc** [comment]
Подогнал под макет, иногда есть рассинхрон в пару пикселей, когда дело доходит до шрифтов, на всякий случай прикреплю несколько скринов PerfectPixel'ем, как это у меня выглядит 

![signin](https://user-images.githubusercontent.com/71395653/111117591-4e4c1980-859a-11eb-9a6f-ff37a268ebda.png)
![filter](https://user-images.githubusercontent.com/71395653/111117608-53a96400-859a-11eb-813a-a2d78d4a6e7b.png)
![footer](https://user-images.githubusercontent.com/71395653/111117614-55732780-859a-11eb-84e2-f7ca721dacec.png)
![landing](https://user-images.githubusercontent.com/71395653/111117616-56a45480-859a-11eb-9cb6-1770c4826f1d.png)
![registr](https://user-images.githubusercontent.com/71395653/111117628-5ad07200-859a-11eb-9b16-fcf228960f64.png)
![details](https://user-images.githubusercontent.com/71395653/111117605-52783700-859a-11eb-8940-86c7546179ce.png)

Я ишью закрывать не буду, если будут замечания, отпишите их сюда, постараюсь оперативно исправить)

**Comment by kate-fsd** [comment]
По поводу центрирования для обоих случаев - есть очень похожий кейс в good practices https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#1.11.
В целом все хорошо

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/119230061-4a50f080-bb23-11eb-92a9-7931007140ba.png)

**Comment by kate-fsd** [comment]
Еще проверь пожалуйста registration, у меня не сходится, но у меня возможно картинка не та
