### ISSUE TITLE
Инпуты, дропдауны

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#7]
Запрети ввод текста в дропдаунах и календарях
![image](https://user-images.githubusercontent.com/66846004/111439408-65b01180-8716-11eb-8312-8aaf391fb9ab.png)

В дропдаунах я б тебе предложила сразу подставлять строку при нажатии на +-, как это сделано в календарях, но это на твое усмотрение)

И закрывай дропдаун (и календарь) при клике на стрелочку, если он в этот момент открыт

**Comment by kate-fsd** [comment]
> И закрывай дропдаун (и календарь) при клике на стрелочку, если он в этот момент открыт

Дропдаун закрывается, календарь нет

**Comment by kate-fsd** [comment]
> Дропдаун закрывается, календарь нет

не исправлено

**Comment by kate-fsd** [comment]
Не исправлено

**Comment by Euyevnc** [comment]
Ну,  в последней версии всё работает
![clndr](https://user-images.githubusercontent.com/71395653/113989177-6271f680-987a-11eb-9230-89d004f549b5.gif)

**Comment by kate-fsd** [comment]
Через раз, это не проблема с мышкой, с тачпадом то же

![Peek 2021-04-09 21-45](https://user-images.githubusercontent.com/66846004/114226988-08a62500-997d-11eb-99a2-b37e36ea438e.gif)
