### ISSUE TITLE
Подключение библиотек

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/Ui-kit-and-SitePages#9]
По возможности все нужно подключать через npm - datepicker, fontawesome, materialicons ... Проверь, есть ли еще  библиотеки/плагины/шрифты

**Comment by Euyevnc** [comment]
Я подключил через npm Font awesome и material icons, что наверное, стоило сразу сделать. Для Material'а font-face всё равно пришлось переопределять, т.к. в файле пакета не был подключён svg, хоть он там и был, 
С другими же шрифтами всё хуже, т.к. пакеты с npm я включил в зависимости, но во всех них из форматов лишь woff и woff2, так что пришлось оставить как есть 
А с плагинами такая ситуация, что эти 3, что лежат в папке plugins, были мною изменены, поэтому и не использую npm. Возможно, можно было бы их залить туда, но не уверен, что это будет корректно )

**Comment by kate-fsd** [comment]
Вообще лучше так не делать без необходимости, потому что теперь ответственность за этот код на тебе. Если допустим найдется баг, и будет исправлен в официальном репозитории, ты не сможешь просто обновить плагин, придется исправлять у себя вручную. Лучше пользоваться предоставленными API и переопределять стили, а если чего то не хватает, попробовать поискать другое решение. Но этот ишью я закрою
